### ISSUE TITLE
Children not set inside connected callback

### ISSUE THREAD

**Issue by lukas-schardt** [webtides/element-js#15]
If you are trying to access the children of the current element inside the `connected`-Hook, the HTMLCollection will be empty.

```
    connected() {
        this._children = [ ...this.children ];
        console.log(this._children, this.children );
    }
```

But if we are requesting an animation frame it works and the array is not empty anymore

```
    connected() {
        requestAnimationFrame(() => {
            this._children = [ ...this.children ];
            console.log(this._children, this.children );
        });
    }
```

**Comment by quarkus** [comment]
This occured due to early script execution time. It seems like the browser does not know the children of a custom element in the connectedCallback when the script is executed before the elements dom position.

`<html>

<head>
    <script>

        class Test extends HTMLElement {

            connectedCallback() {
                console.log('A', Array.from(this.children))
            }

        }

        customElements.define('test-a', Test);
    </script>

</head>


<body>

<test-a>
    <h1>hello a</h1>
</test-a>

<test-b>
    <h1>hello b</h1>
</test-b>


<script>

    class TestB extends HTMLElement {

        connectedCallback() {
            console.log('B', Array.from(this.children))
        }

    }

    customElements.define('test-b', TestB);
</script>
</body>


</html>`
